In [11]:
import torch as t

x = t.Tensor([5,3])
y = t.Tensor([2,1])

tensor([10.,  3.])


In [14]:
print(x*y)
print(x+y)
print(x-y)

tensor([10.,  3.])
tensor([7., 4.])
tensor([3., 2.])


In [15]:
x.shape

torch.Size([2])

In [16]:
x = t.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [17]:
x.shape

torch.Size([2, 5])

In [5]:
y = t.rand([2,5])
print(y)

tensor([[0.8856, 0.5729, 0.3714, 0.3941, 0.2199],
        [0.8928, 0.3163, 0.6831, 0.8665, 0.2221]])


In [8]:
y = y.view([1,10])

tensor([[0.8856, 0.5729, 0.3714, 0.3941, 0.2199, 0.8928, 0.3163, 0.6831, 0.8665,
         0.2221]])