In [1]:
import torch as t

x = t.Tensor([5,3])
y = t.Tensor([2,1])

In [2]:
print(x*y)
print(x+y)
print(x-y)

tensor([10.,  3.])
tensor([7., 4.])
tensor([3., 2.])


In [3]:
x.shape

torch.Size([2])

In [4]:
x = t.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [5]:
x.shape

torch.Size([2, 5])

In [6]:
y = t.rand([2,5])
print(y)

tensor([[0.4058, 0.9887, 0.3045, 0.0945, 0.2829],
        [0.3748, 0.9876, 0.5724, 0.9139, 0.8911]])


In [9]:
y = y.view([1,10])

In [10]:
print(y)

tensor([[0.4058, 0.9887, 0.3045, 0.0945, 0.2829, 0.3748, 0.9876, 0.5724, 0.9139,
         0.8911]])
